### ISSUE TITLE
blind screen

### ISSUE THREAD

**Issue by aleksandrm8** [Freescale/u-boot-fslc#1]
I have blind screen on mx6q when use this u-boot.

I.E. i use:
make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- distclean
make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd_config
make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd
sudo dd if=./u-boot.bin of=/dev/sdb bs=512 seek=2 skip=2 conv=fsync

**Comment by otavio** [comment]
Yes; please use:

sudo dd if=u-boot.imx of=... bs=512 seek=2 conv=fsync

Drop the skip=2 and use the u-boot.imx file.

On Tue, Oct 8, 2013 at 12:06 PM, aleksandrm8 notifications@github.comwrote:

> I have blind screen on mx6q when use this u-boot.
> 
> I.E. i use:
> make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- distclean
> make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd_config
> make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd
> sudo dd if=./u-boot.bin of=/dev/sdb bs=512 seek=2 skip=2 conv=fsync
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Freescale/u-boot-imx/issues/1
> .

## 

Otavio Salvador                             O.S. Systems
http://www.ossystems.com.br        http://code.ossystems.com.br
Mobile: +55 (53) 9981-7854            Mobile: +1 (347) 903-9750

**Comment by aleksandrm8** [comment]
Thank you wery much. All working fine!

**Comment by aleksandrm8** [comment]
I have new issue now. Hope you may help me.

I use kernel linux-mainline from this repo. 
On sd already exist u-boot. I use commands that i wrote above.
My commands for uImage:

make ARCH=arm distclean
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- imx_v6_v7_defconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage LOADADDR=0x10008000
sudo dd if=./arch/arm/boot/uImage of=/dev/sdb seek=2048 conv=fsync

As result i have

U-Boot 2013.07-00001-gcba5372 (Oct 08 2013 - 18:59:47)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: MX6-SabreSD
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
In:    serial
Out:   serial
Err:   serial
Net:   Phy not found
PHY reset timed out
FEC [PRIME]
Hit any key to stop autoboot:  0
mmc2(part 0) is current device

MMC read: dev # 2, block # 2048, count 8192 ... 8192 blocks read: OK
Wrong Image Format for bootm command
ERROR: can't get kernel image!
