### ISSUE TITLE
fetch u-boot-fslc always error.

### ISSUE THREAD

**Issue by yjdwbj** [Freescale/u-boot-fslc#12]
WARNING: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Failed to fetch URL git://github.com/Freescale/u-boot-fslc.git;branch=2016.09+fslc, attempting MIRRORS if available
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress git://github.com/Freescale/u-boot-fslc.git refs/*:refs/* failed with exit code 128, output:
fatal: Refusing to fetch into current branch refs/heads/2015.10+fslc of non-bare repository

DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Trying MIRRORS
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; git -c core.fsyncobjectfiles=0 branch --contains 0dea106b4985c15c055e7ae187b05a53d6a82a41 --list 2016.09+fslc 2> /dev/null | wc -l
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; git -c core.fsyncobjectfiles=0 branch --contains 0dea106b4985c15c055e7ae187b05a53d6a82a41 --list 2016.09+fslc 2> /dev/null | wc -l
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; git -c core.fsyncobjectfiles=0 remote rm origin
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; git -c core.fsyncobjectfiles=0 remote add --mirror=fetch origin git://github.com/Freescale/u-boot-fslc.git
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher accessed the network with the command LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress git://github.com/Freescale/u-boot-fslc.git refs/*:refs/*
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress git://github.com/Freescale/u-boot-fslc.git refs/*:refs/*
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Mirror fetch failure for url http://downloads.yoctoproject.org/mirror/sources/git2_github.com.Freescale.u-boot-fslc.git.tar.gz (original url: git://github.com/Freescale/u-boot-fslc.git;branch=2016.09+fslc)
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress git://github.com/Freescale/u-boot-fslc.git refs/*:refs/* failed with exit code 128, output:
fatal: Refusing to fetch into current branch refs/heads/2015.10+fslc of non-bare repository

DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher accessed the network with the command /usr/bin/env wget -t 2 -T 30 -nv --passive-ftp --no-check-certificate -P /home/michael/3TB-DISK/poky/build/downloads 'http://sources.openembedded.org/git2_github.com.Freescale.u-boot-fslc.git.tar.gz'
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; /usr/bin/env wget -t 2 -T 30 -nv --passive-ftp --no-check-certificate -P /home/michael/3TB-DISK/poky/build/downloads 'http://sources.openembedded.org/git2_github.com.Freescale.u-boot-fslc.git.tar.gz' --progress=dot -v
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Mirror fetch failure for url http://sources.openembedded.org/git2_github.com.Freescale.u-boot-fslc.git.tar.gz (original url: git://github.com/Freescale/u-boot-fslc.git;branch=2016.09+fslc)
DEBUG: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; /usr/bin/env wget -t 2 -T 30 -nv --passive-ftp --no-check-certificate -P /home/michael/3TB-DISK/poky/build/downloads 'http://sources.openembedded.org/git2_github.com.Freescale.u-boot-fslc.git.tar.gz' --progress=dot -v failed with exit code 8, output:
--2017-03-18 20:26:43--  http://sources.openembedded.org/git2_github.com.Freescale.u-boot-fslc.git.tar.gz
Resolving sources.openembedded.org (sources.openembedded.org)... 140.211.169.161
Connecting to sources.openembedded.org (sources.openembedded.org)|140.211.169.161|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-18 20:26:58 ERROR 404: Not Found.

ERROR: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-M1NotMsBBL,guid=e19368ace0df6d9b0b297e6b58cd1c37"; export SSH_AGENT_PID="4224"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/michael/3TB-DISK/poky/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin/arm-poky-linux-gnueabi:/home/michael/3TB-DISK/poky/build/tmp/sysroots/imx28evk/usr/bin/crossscripts:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/usr/bin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/sbin:/home/michael/3TB-DISK/poky/build/tmp/sysroots/x86_64-linux/bin:/home/michael/3TB-DISK/poky/scripts:/home/michael/3TB-DISK/poky/bitbake/bin:/home/michael/.sdkman/candidates/springboot/current/bin:/home/michael/.sdkman/candidates/groovy/current/bin:/home/michael/.sdkman/candidates/gradle/current/bin:/home/michael/3TB-DISK/altera/13.0/quartus/linux64/:/home/michael/3TB-DISK/Android/Sdk//ndk-bundle:/home/michael/3TB-DISK/Android/Sdk//tools:/home/michael/3TB-DISK/Android/Sdk//platform-tools:/home/michael/3TB-DISK/Android/Sdk//build-tools:/home/michael/IDE_DIR/jdk1.8.0_112/bin:/opt/go/bin:/home/michael/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/sbin:/sbin:/home/michael/arm-2013.05/bin/:/home/michael/hitech/picc/9.83/bin:/usr/local/sbin:/home/michael/usr/node-v4.2.1-linux-x64/bin:/opt/google_appengine:/home/michael/Embedded-System/gcc-arm-none-eabi-4_9-2015q3/bin:/opt/FriendlyARM/toolschain/4.4.3/bin:/opt/julia/bin:/home/michael/3TB-DISK/github/zcash/depends/x86_64-unknown-linux-gnu/bin:/home/michael/SOFT-LIBRAR/node-v6.9.2-linux-x64/bin:/home/michael/Android/Sdk/platform-tools"; export HOME="/home/michael"; LANG=C git -c core.fsyncobjectfiles=0 fetch -f --prune --progress git://github.com/Freescale/u-boot-fslc.git refs/*:refs/* failed with exit code 128, output:
fatal: Refusing to fetch into current branch refs/heads/2015.10+fslc of non-bare repository

ERROR: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Fetcher failure for URL: 'git://github.com/Freescale/u-boot-fslc.git;branch=2016.09+fslc'. Unable to fetch URL from any source.
ERROR: u-boot-fslc-v2016.09+gitAUTOINC+0dea106b49-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/michael/3TB-DISK/poky/build/tmp/work/imx28evk-poky-linux-gnueabi/u-boot-fslc/v2016.09+gitAUTOINC+0dea106b49-r0/temp/log.do_fetch.9682
ERROR: Task (/home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc_2016.09.bb:do_fetch) failed with exit code '1'
DEBUG: Teardown for bitbake-worker
NOTE: Tasks Summary: Attempted 2050 tasks of which 2049 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc_2016.09.bb:do_fetch
Summary: There was 1 WARNING message shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
michael@debian:~/3TB-DISK/poky/build$ vi /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc_2016.09.bb
michael@debian:~/3TB-DISK/poky/build$ vi /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-
u-boot-fslc_2016.09.bb          u-boot-fslc.inc                 u-boot-fslc-mxsboot_2016.09.bb  u-boot-imx_2015.04.bb           u-boot-imx-mfgtool_2015.04.bb   u-boot-ls1/                     u-boot-ls1_2015.01.bb           u-boot-mfgtool.inc
michael@debian:~/3TB-DISK/poky/build$ vi /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc.inc 
michael@debian:~/3TB-DISK/poky/build$ vi /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc_2016.09.bb
michael@debian:~/3TB-DISK/poky/build$ cat /home/michael/3TB-DISK/poky/meta-fsl-arm/recipes-bsp/u-boot/u-boot-fslc_2016.09.bb
include u-boot-fslc.inc

PV = "v2016.09+git${SRCPV}"

SRCREV = "0dea106b4985c15c055e7ae187b05a53d6a82a41"
SRCBRANCH = "2016.09+fslc"

**Comment by otavio** [comment]
It seems to be a firewall issue. Take a look at your network firewall and make sure it is not blocking it.
