### ISSUE TITLE
yocto build error with SATA

### ISSUE THREAD

**Issue by d4s** [Freescale/u-boot-fslc#14]
Building for MACHINE=cubox-i I have the problem described in 43d4159d1853563b9c7c125109b22ca54d343832 commit:

| /srv/d4s/ARM/cubox-i/yocto/tmp/work/cubox_i-poky-linux-gnueabi/u-boot-fslc/v2017.07+gitAUTOINC+f5f42f39f3-r0/git/include/config_distro_bootcmd.h:161:2: error: expected '}' before 'BOOT_TARGET_DEVICES_references_SATA_without_CONFIG_CMD_SATA'
|   BOOT_TARGET_DEVICES_references_SATA_without_CONFIG_CMD_SATA

But I have no build issue with commit 43d4159d reverted.

**Comment by fabioestevam** [comment]
On Tue, Jul 18, 2017 at 3:32 PM, Denis Pynkin <notifications@github.com>
wrote:

> Building for MACHINE=cubox-i I have the problem described in 43d4159
> <https://github.com/Freescale/u-boot-fslc/commit/43d4159d1853563b9c7c125109b22ca54d343832>
> commit:
>
> | /srv/d4s/ARM/cubox-i/yocto/tmp/work/cubox_i-poky-linux-
> gnueabi/u-boot-fslc/v2017.07+gitAUTOINC+f5f42f39f3-r0/git/
> include/config_distro_bootcmd.h:161:2: error: expected '}' before
> 'BOOT_TARGET_DEVICES_references_SATA_without_CONFIG_CMD_SATA'
> | BOOT_TARGET_DEVICES_references_SATA_without_CONFIG_CMD_SATA
>

This has been fixed by commit:
https://github.com/Freescale/u-boot-fslc/commit/43d4159d1853563b9c7c125109b22ca54d343832

**Comment by d4s** [comment]
Please re-read my report -- I have this issue **with** 43d4159 but have a clean build if I revert it

**Comment by fabioestevam** [comment]
On Tue, Jul 18, 2017 at 3:48 PM, Denis Pynkin <notifications@github.com>
wrote:

> Please re-read my report -- I have this issue *with* 43d4159
> <https://github.com/Freescale/u-boot-fslc/commit/43d4159d1853563b9c7c125109b22ca54d343832>
> but have a clean build if I revert it
>
Sorry about that.

I have just confirmed the failure.

This commit went into mainline U-Boot to fix the build issue.

43d4159
<https://github.com/Freescale/u-boot-fslc/commit/43d4159d1853563b9c7c125109b22ca54d343832>
should
be reverted from u-boot-fslc.

Otavio, can you please revert it?

**Comment by d4s** [comment]
Thanks!

**Comment by otavio** [comment]
@d4s do you mind in preparing a pull request fixing it?

**Comment by d4s** [comment]
Sure! Ready.

**Comment by otavio** [comment]
Fixed by #15

**Comment by otavio** [comment]
On Tue, Jul 18, 2017 at 4:28 PM, Denis Pynkin <notifications@github.com>
wrote:

> Sure! Ready.
>

I merged it; please send a bump for the recipe so we are all happy ;-)

-- 
Otavio Salvador                             O.S. Systems
http://www.ossystems.com.br        http://code.ossystems.com.br
Mobile: +55 (53) 9981-7854            Mobile: +1 (347) 903-9750

**Comment by d4s** [comment]
Done! Thank you for guiding me ;)
