### ISSUE TITLE
Developing on a fork from u-boot-fslc is a pain

### ISSUE THREAD

**Issue by kjivan** [Freescale/u-boot-fslc#17]
Is there a merging strategy to pull the latest changes/fixes from this repo into a fork?  Typically a project has a master and all the commits can be pulled from there. Simply merging a new branch to an old branch causes conflicts.

eg. 2017.07+fslc -> 2016.03+fslc caused the following conflicts:

`Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by them: arch/arm/cpu/armv7/mx6/Kconfig
        deleted by them: arch/arm/cpu/armv7/mx6/clock.c
        deleted by them: arch/arm/cpu/armv7/mx6/ddr.c
        deleted by them: arch/arm/cpu/armv7/mx6/soc.c
        deleted by them: arch/arm/cpu/armv7/mx7/Kconfig
        deleted by them: arch/arm/cpu/armv7/mx7/soc.c
        deleted by them: arch/arm/imx-common/cpu.c
        both added:      board/ccv/xpress/imximage.cfg
        both added:      board/ccv/xpress/spl.c
        both added:      board/ccv/xpress/xpress.c
        both added:      board/ge/bx50v3/bx50v3.c
        both added:      board/warp7/MAINTAINERS
        both added:      board/warp7/imximage.cfg
        both added:      board/warp7/warp7.c
        both added:      configs/ge_b450v3_defconfig
        both added:      configs/ge_b650v3_defconfig
        both added:      configs/ge_b850v3_defconfig
        both modified:   configs/mx28evk_defconfig
        both modified:   configs/mx6sxsabreauto_defconfig
        both modified:   configs/mx6sxsabresd_defconfig
        both modified:   configs/mx6sxsabresd_spl_defconfig
        both modified:   configs/mx7dsabresd_defconfig
        both added:      configs/warp7_defconfig
        both added:      configs/xpress_defconfig
        both added:      configs/xpress_spl_defconfig
        both modified:   include/configs/embestmx6boards.h
        both added:      include/configs/ge_bx50v3.h
        both modified:   include/configs/m53evk.h
        both modified:   include/configs/mx28evk.h
        both modified:   include/configs/mx6cuboxi.h
        deleted by them: include/configs/mx6qsabreauto.h
        both modified:   include/configs/mx6sabre_common.h
        both modified:   include/configs/mx6sabresd.h
        both modified:   include/configs/mx7_common.h
        both modified:   include/configs/mx7dsabresd.h
        both modified:   include/configs/wandboard.h
        both added:      include/configs/warp7.h
        both added:      include/configs/xpress.h
`

**Comment by otavio** [comment]
Agreed; the branches are based on releases.

Every release we rebase our patches on top of the new release so I'd suggest you rebase it. Also please send the patches for mainline or here for merge so we reduce the fork when possible.
