### ISSUE TITLE
Wandboard: wrong mmc partition used

### ISSUE THREAD

**Issue by tegoo** [Freescale/u-boot-fslc#18]
Seems, that there is a wrong mmc partition specified in finduuid
/include/configs/wandboard.h

`
"finduuid=part uuid mmc 0:1 uuid\0" \
`

Should be 

`
"finduuid=part uuid mmc 0:2 uuid\0" \
`

**Comment by otavio** [comment]
Hello @tegoo 

Thanks for reporting the issue for us. It is not clear which branch you are referring to? Could you clarify?
