### ISSUE TITLE
Wrong Image Format for bootm command

### ISSUE THREAD

**Issue by aleksandrm8** [Freescale/u-boot-fslc#2]
I have new issue now. Hope you may help me.

I use commands for u-boot:

make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- distclean
make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd_config
make arm=ARM CROSS_COMPILE=arm-linux-gnueabihf- mx6qsabresd
sudo dd if=./u-boot.bin of=/dev/sdb bs=512 seek=2 skip=2 conv=fsync

I use kernel linux-mainline from this repo. 

My commands for uImage:
make ARCH=arm distclean
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- imx_v6_v7_defconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage LOADADDR=0x10008000
sudo dd if=./arch/arm/boot/uImage of=/dev/sdb seek=2048 conv=fsync

As result i have

U-Boot 2013.07-00001-gcba5372 (Oct 08 2013 - 18:59:47)

CPU: Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: MX6-SabreSD
DRAM: 1 GiB
MMC: FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
In: serial
Out: serial
Err: serial
Net: Phy not found
PHY reset timed out
FEC [PRIME]
Hit any key to stop autoboot: 0
mmc2(part 0) is current device

MMC read: dev # 2, block # 2048, count 8192 ... 8192 blocks read: OK
Wrong Image Format for bootm command
ERROR: can't get kernel image!

**Comment by otavio** [comment]
Please report this to Freescale Community; you should check how we do this in Yocto as it is already solved there.

Otherwise I can offer you our support services were we can help you directly.

**Comment by aleksandrm8** [comment]
Thank you very much, Otavio. I am already create post here https://community.freescale.com/message/354562#354562
but I have no eny reply.
I am going to use Yocto as you advice.
Can you rovide me some howto or manual about Yocto?

Regards

**Comment by santosh-yadav** [comment]
Hi,
i am new to imx6 board and i am facing the same issue mentioned above

U-Boot 2013.10-Q7-QD-256MBx446)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: SECO Q7
I2C:   ready
DRAM:  1 GiB
Boot:  Ext SD
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
**\* Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   using phy at 6
FEC
Hit any key to stop autoboot:  0 
mmc0(part 0) is current device
*\* File not found /boot/uImage **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
MX6Q SECO_Q7 U-Boot >

above is the u-boot log i abtained through debug seral poart in minicom .
can any one help me with this issue . 
@aleksandrm8 wanted to know did this work with yocto if yes can you send me the steps plz

thanks in advance.
