### ISSUE TITLE
Not working with WARP7

### ISSUE THREAD

**Issue by oksbwn** [Freescale/u-boot-fslc#24]
When i run the command MAKE, I am getting error as described below, Please help me on this, I am newbie in these things,

make
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config.h
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
*** Your GCC is older than 6.0 and will not be supported starting in v2018.01.
  CHK     include/config/uboot.release
  UPD     include/config/uboot.release
  CHK     include/generated/version_autogenerated.h
  UPD     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CC      lib/asm-offsets.s
lib/asm-offsets.c:1:0: error: bad value (armv5) for -march= switch
 /*
 ^
make[1]: *** [lib/asm-offsets.s] Error 1
make: *** [prepare0] Error 2

**Comment by otavio** [comment]
What are the build options and toolchain you are using?

**Comment by fabioestevam** [comment]
Hi Bikash,

On Thu, Apr 26, 2018 at 6:45 AM, Bikash Narayan Panda <
notifications@github.com> wrote:

> When i run the command MAKE, I am getting error as described below, Please
> help me on this, I am newbie in these things,
>
> make
> scripts/kconfig/conf --silentoldconfig Kconfig
> CHK include/config.h
> UPD include/config.h
> CFG u-boot.cfg
> GEN include/autoconf.mk
> GEN include/autoconf.mk.dep
> *** Your GCC is older than 6.0 and will not be supported starting in
> v2018.01.
>
You need a newer toolchain.



> CHK include/config/uboot.release
> UPD include/config/uboot.release
> CHK include/generated/version_autogenerated.h
> UPD include/generated/version_autogenerated.h
> CHK include/generated/timestamp_autogenerated.h
> UPD include/generated/timestamp_autogenerated.h
> CC lib/asm-offsets.s
> lib/asm-offsets.c:1:0: error: bad value (armv5) for -march= switch
>

Looks like you missed to export the toolchain.

Something like this:
export ARCH=arm
export CROSS_COMPILE=/usr/bin/arm-linux-gnueabi-
