### ISSUE TITLE
Disable PSCI support

### ISSUE THREAD

**Issue by DorfilIkatu** [Freescale/u-boot-fslc#28]
Hi,

I'm trying to disable PSCI support on u-boot, adding "CONFIG_ARMV7_PSCI=n" to my defconfig file. But after this change, the u-boot does not compile anymore. It is failing when running mkimage:

"./tools/mkimage -n board/.../imximage_32bit_ddr3.cfg.cfgtmp -T imximage -e 0x87800000 -d u-boot.bin u-boot.imx
 ./tools/mkimage: Write error on u-boot.imx: Bad address"

Any ideas?
Thanks

**Comment by otavio** [comment]
Please contact the U-Boot mailing list as this is the best way to get support. I am closing it here.
