### ISSUE TITLE
how can i boot form sata ,with imx6q_sabresd ,thanks

### ISSUE THREAD

**Issue by wuyankun** [Freescale/u-boot-fslc#3]
U-Boot 2009.08-dirty (Mar 10 2014 - 19:30:06)

CPU: Freescale i.MX6 family TO1.2 at 792 MHz
Thermal sensor with ratio = 187
Temperature:   28 C, calibration data 0x5a04db7d
mx6q pll1: 792MHz
mx6q pll2: 528MHz
mx6q pll3: 480MHz
mx6q pll8: 50MHz
ipg clock     : 66000000Hz
ipg per clock : 66000000Hz
uart clock    : 80000000Hz
cspi clock    : 60000000Hz
ahb clock     : 132000000Hz
axi clock   : 264000000Hz
emi_slow clock: 132000000Hz
ddr clock     : 528000000Hz
usdhc1 clock  : 198000000Hz
usdhc2 clock  : 198000000Hz
usdhc3 clock  : 198000000Hz
usdhc4 clock  : 198000000Hz
nfc clock     : 24000000Hz
Board: i.MX6Q-SABRESD: RevC Board: 0x63312 [POR ]
Boot Device: SATA
I2C:   ready
DRAM:   1 GB
MMC:   usdhc_gpio_init() fail!FSL_USDHC: 0,FSL_USDHC: 1,FSL_USDHC: 2,FSL_USDHC: 3
AHCI 0001.0300 32 slots 1 ports 3 Gbps 0x1 impl SATA mode
flags: ncq stag pm led clo only pmp pio slum part
SATA Device Info:
S/N:       TE9B113QKWKGWP
Product model number: Hitachi HTS545032A7E380
Firmware version: GGBOA7A0
Capacity: 625142448 sectors
In:    serial
Out:   serial
Err:   serial
unsupported boot devices
Found PFUZE100! deviceid=10,revid=10
Net:   got MAC address from IIM: 00:04:9f:02:62:3b
FEC0 [PRIME]
Hit any key to stop autoboot:  0

SATA read: device 0 block # 2048, count 8192 ... 8192 blocks read: OK

SATA read: device 0 block # 12288, count 768 ... 768 blocks read: OK
Wrong Image Format for bootm command
ERROR: can't get kernel image!
MX6Q SABRESD U-Boot > print
bootdelay=3
baudrate=115200
ipaddr=192.168.1.103
serverip=192.168.1.101
netmask=255.255.255.0
netdev=eth0
ethprime=FEC0
splashimage=0x30000000
splashpos=m,m
lvds_num=1
ethact=FEC0
fastboot_dev=/dev/sda
bootargs_base=setenv bootargs console=ttymxc0,115200
bootargs_sata=setenv bootargs ${bootargs} console=tty1 root=/dev/sda1 rootwait rw video=mxcdi1fb:GBR24,VGA-XGA dil_primary vga
bootcmd=run bootcmd_sata;bootm ${loadaddr} ${rd_loadaddr}
bootcmd_sata=sata read ${loadaddr} 0x800 0x2000;sata read ${rd_loadaddr} 0x3000 0x300;
bootargs=console=ttymxc0 init=/init androidboot.console=ttymxc0 vide=mxcdi1fb:RGB666,XGA ldb=di1 di1_primary ip=dhcp gpu_nommu,gpu_memory=64M
loadaddr=0x10800000
rd_loadaddr=0x11000000
stdin=serial
stdout=serial
stderr=serial

Environment size: 753/8188 bytes
MX6Q SABRESD U-Boot >

**Comment by angolini** [comment]
the u-boot version 2009.08 is not the right one to use with imx6qsabre sd.

I suggest you to submit a question in imx.community, or meta-freescale, in case you´re using FSL community BSP.

**Comment by angolini** [comment]
@wuyankun  Please, confirm this it worked and close the issue
