### ISSUE TITLE
Makefile.lib generates wrong syntax dts files

### ISSUE THREAD

**Issue by maquefel** [Freescale/u-boot-fslc#30]
https://github.com/Freescale/u-boot-fslc/blob/7cc38fda11ea92f5d91571215c3022b2d4ed7faf/scripts/Makefile.lib#L302

This produces:
```
\#include "imx7d-sdb-qspi-u-boot.dtsi"
```

Which results in:
```
Error: arch/arm/dts/.imx7d-sdb-qspi.dtb.pre.tmp:47.1-10 syntax error
FATAL ERROR: Unable to parse input tree
```

Dear Masahiro Yamada, i think you ment something like :
```
(cat $<; $(if $(u_boot_dtsi),echo '#include "$(u_boot_dtsi)"')) > $(pre-tmp);
```

**Comment by angolini** [comment]
I'm sorry for having this open for so long.

Have you tested it with newer u-boot versions?
