### ISSUE TITLE
Add support for 'bmode' command on iMX8

### ISSUE THREAD

**Issue by raveslave** [Freescale/u-boot-fslc#33]
It would be great with added support for the `bmode usb` on i.MX8 mini
_i.e. to trigger USB download mode from software_

**Comment by otavio** [comment]
@raveslave agreed. Are you willing to look at this?

**Comment by raveslave** [comment]
I'm an EE, never done uboot development. But would be happy to use it. Any tips on small consultancy companies that might be able to do this?

**Comment by otavio** [comment]
We, at O.S. Systems, can do that if you are willing to sponsor it.

**Comment by a3f** [comment]
FWIW, the magic sequence for i.MX8MM is `mw.l 0x30390094 0x10 ; mw.l 0x30390098 0x40000000` and then doing a warm reset (i.e. without `fsl,ext-reset-output`). [See the barebox commit for more information.](https://lore.barebox.org/barebox/20210803165937.31608-2-a.fatoum@pengutronix.de/)
