### ISSUE TITLE
imx6 uImage not found (porting linux)

### ISSUE THREAD

**Issue by santosh-yadav** [Freescale/u-boot-fslc#4]
Hi,
i am new to imx6 board and i am facing the same issue mentioned above

U-Boot 2013.10-Q7-QD-256MBx446)

CPU: Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: SECO Q7
I2C: ready
DRAM: 1 GiB
Boot: Ext SD
MMC: FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
**\* Warning - bad CRC, using default environment

In: serial
Out: serial
Err: serial
Net: using phy at 6
FEC
Hit any key to stop autoboot: 0
mmc0(part 0) is current device
*\* File not found /boot/uImage **
Wrong Image Format for bootm command
ERROR: can't get kernel image!
MX6Q SECO_Q7 U-Boot >

above is the u-boot log i abtained through debug seral poart in minicom .
can any one help me with this issue .

**Comment by angolini** [comment]
I think your BOOTENV is not feasible. Please, double check.

If you need more help, please, subscribe to meta-freescale and post your question there.

http://freescale.github.io/
https://lists.yoctoproject.org/listinfo/meta-freescale
