### ISSUE TITLE
wrong pad define in arch/arm/dts/imx6ull-pinfunc.h

### ISSUE THREAD

**Issue by GeorgeMakarov** [Freescale/u-boot-fslc#44]
it has define **MX6ULL_PAD_CSI_DATA07__ESAI_T0** while the pad in accordance with reference manual (32.6.112 SW_MUX_CTL_PAD_CSI_DATA07 SW MUX Control Register (IOMUXC_SW_MUX_CTL_PAD_CSI_DATA07)) should be called **MX6ULL_PAD_CSI_DATA07__ESAI_TX0**
And Config Tools for i.MX 10.0 generates dtsi which uses define **MX6ULL_PAD_CSI_DATA07__ESAI_TX0**

**Comment by otavio** [comment]
I believe this should be sent to U-Boot upstream. Am I right @fabioestevam ?

**Comment by fabioestevam** [comment]
Hi George,

On Wed, Nov 17, 2021 at 3:59 AM George Makarov ***@***.***> wrote:
>
> it has define MX6ULL_PAD_CSI_DATA07__ESAI_T0 while the pad in accordance with reference manual (32.6.112 SW_MUX_CTL_PAD_CSI_DATA07 SW MUX Control Register (IOMUXC_SW_MUX_CTL_PAD_CSI_DATA07)) should be called MX6ULL_PAD_CSI_DATA07__ESAI_TX0
> And Config Tools for i.MX 10.0 generates dtsi which used define MX6ULL_PAD_CSI_DATA07__ESAI_TX0

Yes, the current name is incorrect. I checked in the kernel and the
same error is present there too.

I can send a patch to the upstream Linux device tree like this:

--- a/arch/arm/boot/dts/imx6ull-pinfunc.h
+++ b/arch/arm/boot/dts/imx6ull-pinfunc.h
@@ -82,6 +82,11 @@
 #define MX6ULL_PAD_CSI_DATA04__ESAI_TX_FS
0x01F4 0x0480 0x0000 0x9 0x0
 #define MX6ULL_PAD_CSI_DATA05__ESAI_TX_CLK
0x01F8 0x0484 0x0000 0x9 0x0
 #define MX6ULL_PAD_CSI_DATA06__ESAI_TX5_RX0
0x01FC 0x0488 0x0000 0x9 0x0
+/*
+ * As per the Reference Manual, the correct name is ESAI_TX0.
+ * Keep the old name here to avoid breakage.
+ */
 #define MX6ULL_PAD_CSI_DATA07__ESAI_T0
0x0200 0x048C 0x0000 0x9 0x0
+#define MX6ULL_PAD_CSI_DATA07__ESAI_TX0
0x0200 0x048C 0x0000 0x9 0x0

May I send it adding a Reported-by tag from you?

If so, what is your email address, please?

Thanks

**Comment by GeorgeMakarov** [comment]
Thank you for quick response. my email is georgemakarov1@gmail.com
I wonder why nobody noticed the incorrect name before, while this define was added 5 years ago

**Comment by fabioestevam** [comment]
On Thu, Nov 18, 2021 at 2:55 AM George Makarov ***@***.***> wrote:
>
> Thank you for quick response. my email is ***@***.***
> I wonder why nobody noticed the incorrect name before, while this define was added 5 years ago

Done. I have submitted a patch for Linux and U-Boot.

Thanks for reporting.
