### ISSUE TITLE
mxc_nand lacking support?

### ISSUE THREAD

**Issue by woutervanh** [Freescale/u-boot-fslc#45]
Is it just me, or is mxc_nand (nand for imx53) lacking quiet some things?
It does not support ONFI (READID on address 0x20 is just ignoring the address and reading from 0, so returning the normal ID)
It does not support 4k flashes (largepage is just 2k)
I want to support MT29F8G08ABABAWP, which is a 4k-paged 1GiB flash. And even after adding it to the nand list manually and being detected, it spits out tons of ECC errors

**Comment by otavio** [comment]
Possibly. I think this ought to be dealt on U-Boot upstream. Do you mind opening a thread on their mailing list?

Cc: @fabioestevam

**Comment by fabioestevam** [comment]
On Wed, Nov 17, 2021 at 8:11 AM Otavio Salvador
***@***.***> wrote:
>
> Possibly. I think this ought to be dealt on U-Boot upstream. Do you mind opening a thread on their mailing list?
>
> Cc: @fabioestevam

Yes, the U-Boot list is the right place for discussing this.

**Comment by woutervanh** [comment]
Ok, I'll give it a try. Nothing else than mailing lists?

**Comment by fabioestevam** [comment]
On Wed, Nov 17, 2021 at 10:46 AM Wouter Vanhauwaert
***@***.***> wrote:
>
> Ok, I'll give it a try. Nothing else than mailing lists?

Is it working properly in Linux?

If so, you could try aligning the Linux driver with the U-Boot one.

**Comment by woutervanh** [comment]
Well, it was detected by linux driver, but also not working. After limiting the oobsize to 218 and some other things, it seems to work ok. (barebox is a good reference)
And indeed, I tried modifying the mxc_nand.c in uboot according to the kernel/barebox patches, but that's no easy task. They do not resemble at all... I'm now upto a point where it kind of works. I can flash_erase it in user space, create ubi volumes and read these ubi volumes back in u-boot. However, there must still be something wrong, as I'm unable to use the flash if it's erase.chip't in u-boot. I have to first flash_erase it in user space and afterwards it works in uboot and linux. So still some figuring

**Comment by fabioestevam** [comment]
On Wed, Nov 17, 2021 at 11:04 AM Wouter Vanhauwaert
***@***.***> wrote:
>
> Well, it was detected by linux driver, but also not working. After limiting the oobsize to 218 and some other things, it seems to work ok. (barebox is a good reference)

My suggestion is to fix this in the kernel first. After that, the
U-Boot mxc nand driver can be reworked to follow the Linux driver.
