### ISSUE TITLE
Broken support for Hummingboard i2

### ISSUE THREAD

**Issue by agherzan** [Freescale/u-boot-fslc#7]
Using HEAD of default branch 2015.14, my new Hummingboard i2 stuck at 
"U-Boot SPL 2015.04-00129-g10aced3 (May 29 2015 - 01:43:12)"

Reproduced in yocto (U-Boot SPL 2015.04+fslc+gb16ec2d) and using fedora arm toolchain.

Reproduce steps:
$ make mrproper
$ make mx6cuboxi_defconfig
$ make
$ sudo dd if=SPL of=/dev/sdX bs=1K seek=1
$ sudo dd if=u-boot.img of=/dev/sdX bs=1K seek=42

It seems like SPL can't load the uboot image.
The cuboxi uboot fork works just fine: git://github.com/SolidRun/u-boot-imx6.git;branch=imx6 .

**Comment by fabioestevam** [comment]
Hi Andrei,

On Thu, May 28, 2015 at 8:47 PM, Andrei Gherzan notifications@github.com
wrote:

> Using HEAD of default branch 2015.14, my new Hummingboard 2i stuck at
> U-Boot SPL 2015.04-00129-g10aced3 (May 29 2015 - 01:43:12)
> 
> Reproduced in yocto and usign fedora arm toolchain.
> 
> Thanks for reporting it.

I don't have a Hummingboard dual to try it.

Just a quick check: how did you flash u-boot.img? Manually or Yocto flashed
automatically for you?

Also, please start a thread about this issue on the U-boot mailing list.

Regards,

Fabio Estevam

**Comment by agherzan** [comment]
Hi Estevam, 

Flashed with yocto and manually (using the provided steps)  : same result.
What is the U-boot mailing list you are referring to? I guess the fslc one? 

Regards, 
Andrei

**Comment by fabioestevam** [comment]
Hi Andrei,

On Thu, May 28, 2015 at 9:02 PM, Andrei Gherzan notifications@github.com
wrote:

> Hi Estevam,
> 
> Flashed with yocto and manually (using the provided steps) : same result.
> What is the U-boot mailing list you are referring to? I guess the fslc one?
> 
> I mean the U-boot development list: u-boot@lists.denx.de

Regards,

Fabio Estevam

**Comment by agherzan** [comment]
Started thread on u-boot@lists.denx.de too but list seems moderated.

**Comment by fabioestevam** [comment]
On Thu, May 28, 2015 at 9:13 PM, Andrei Gherzan notifications@github.com
wrote:

> Started thread on u-boot@lists.denx.de too but list seems moderated.
> 
> Can you test this patch in the meantime?

--- a/board/solidrun/mx6cuboxi/mx6cuboxi.c
+++ b/board/solidrun/mx6cuboxi/mx6cuboxi.c
@@ -536,7 +536,7 @@ static const struct mx6_mmdc_calibration
mx6dl_1g_mmcd_calib
        .p0_mpdgctrl0 =    0x023C0224,
        .p0_mpdgctrl1 =    0x02000220,
        .p1_mpdgctrl0 =    0x02200220,
-       .p1_mpdgctrl1 =    0x02000220,
-       .p1_mpdgctrl1 =    0x02040208,
      .p0_mprddlctl =    0x44444846,
      .p1_mprddlctl =    0x4042463C,
      .p0_mpwrdlctl =    0x32343032,

Also, please enable debug in the ddr code:

--- a/arch/arm/cpu/armv7/mx6/ddr.c
+++ b/arch/arm/cpu/armv7/mx6/ddr.c
@@ -12,6 +12,7 @@
 #include <asm/io.h>
 #include <asm/types.h>

+#define DEBUG
 #if defined(CONFIG_MX6SX)
 /\* Configure MX6SX mmdc iomux */
 void mx6sx_dram_iocfg(unsigned width,

and then please send me the output.

Regards,

Fabio Estevam

**Comment by agherzan** [comment]
Hi,

Unfortunately, no changes in runtime behavior with this patch. Excepting for one thing. Sometimes (1/10 resets) I get:

```
U-Boot SPL 2015.04-00129-g10aced3-dirty (May 29 2015 - 10:47:47)
spl: mmc init failed: err - -17
### ERROR ### Please RESET the board ###
```

Here are the local git changes:

```
diff --git a/arch/arm/cpu/armv7/mx6/ddr.c b/arch/arm/cpu/armv7/mx6/ddr.c
index 86c8354..370e505 100644
--- a/arch/arm/cpu/armv7/mx6/ddr.c
+++ b/arch/arm/cpu/armv7/mx6/ddr.c
@@ -12,6 +12,8 @@
 #include <asm/io.h>
 #include <asm/types.h>

+#define DEBUG
+
 #if defined(CONFIG_MX6SX)
 /* Configure MX6SX mmdc iomux */
 void mx6sx_dram_iocfg(unsigned width,
diff --git a/board/solidrun/mx6cuboxi/mx6cuboxi.c b/board/solidrun/mx6cuboxi/mx6cuboxi.c
index d15c726..4682f91 100644
--- a/board/solidrun/mx6cuboxi/mx6cuboxi.c
+++ b/board/solidrun/mx6cuboxi/mx6cuboxi.c
@@ -536,7 +536,7 @@ static const struct mx6_mmdc_calibration mx6dl_1g_mmcd_calib = {
        .p0_mpdgctrl0 =    0x023C0224,
        .p0_mpdgctrl1 =    0x02000220,
        .p1_mpdgctrl0 =    0x02200220,
-       .p1_mpdgctrl1 =    0x02000220,
+       .p1_mpdgctrl1 =    0x02040208,
        .p0_mprddlctl =    0x44444846,
        .p1_mprddlctl =    0x4042463C,
        .p0_mpwrdlctl =    0x32343032,
```

Regards,
Andrei

**Comment by fabioestevam** [comment]
Andrei,

On Fri, May 29, 2015 at 5:51 AM, Andrei Gherzan notifications@github.com
wrote:

> Hi,
> 
> Unfortunately, no changes in runtime behavior with this patch with this
> patch. Excepting for one thing. Sometimes (1/10 resets) I get:
> 
> I noticed that hummingboard dual-lite was picking the incorrect calibration
> struct.

Just fixed and sent a path to the U-boot list.

Please let me know if it fixes the problem.

Regards,

Fabio Estevam

**Comment by agherzan** [comment]
Tested and works. Thanks.
